config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :subforums do
    resources :posts, except: [:index] do
      member do
        post "upvote"
        post "downvote"
      end

      resources :comments, except: [:index] do
        member do
          post "upvote"
          post "downvote"
        end
      end
    end
  end

  root to: redirect("/users/new")
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  body              :text             not null
#  author_id         :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord
  include Votable

  validates :body, :author, :post, presence: true
  validates :parent_comment, presence: true, allow_nil: true

  belongs_to(
    :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User
  )

  belongs_to :post

  has_one(
    :subforum,
    through: :post,
    source: :subforum
  )

  has_many(
    :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    dependent: :destroy
  )

  belongs_to(
    :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true
  )

  def create_preview
    if self.body.length > 100
      return self.body[0..99] + "..."
    else
      return self.body
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in, only: [:create, :new, :edit, :update, :destroy]
  before_action :require_current_user_owns_comment, only: [:edit, :update, :destroy]

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = params[:post_id]
    @post = @comment.post
    @subforum = @comment.subforum

    if @comment.save
      redirect_to subforum_post_url(@subforum, @comment.post_id)
    else
      if @comment.parent_comment_id
        flash[:errors] = @comment.errors.full_messages
        redirect_to subforum_post_comment_url(@subforum, @comment.post_id, @comment.parent_comment_id)
      else
        flash.now[:errors] = @comment.errors.full_messages
        render :new
      end
    end
  end

  def new
    @comment = Comment.new
    @post = Post.find_by(id: params[:post_id])
    @subforum = Subforum.find_by(id: params[:subforum_id])
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @subforum = @comment.subforum
  end

  def show
    @comment = Comment.find(params[:id])
    @child_comments = @comment.child_comments

    @post = @comment.post
    @subforum = @comment.subforum

    @child_comment = @comment.child_comments.new
  end

  def update
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @subforum = @comment.subforum

    if @comment.update(comment_params)
      redirect_to subforum_post_comment_url(params[:subforum_id], @comment.post_id, @comment)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.delete
    redirect_to subforum_post_url(params[:subforum_id], @comment.post_id)
  end

  def upvote
    vote(1)
  end

  def downvote
    vote(-1)
  end

  private

  def require_current_user_owns_comment
    return if current_user.comments.find_by(id: params[:id])
    @comment = Comment.find(params[:id])
    flash[:errors] = ["You did not make this comment"]
    redirect_to subforum_post_comment_url(params[:subforum_id], @comment.post_id, @comment)
  end

  def comment_params
    params.require(:comment).permit(:body, :parent_comment_id)
  end

  def vote(value)
    @comment = Comment.find(params[:id])
    @subforum = @comment.subforum
    @vote = @comment.votes.find_or_initialize_by(user: current_user)

    unless @vote.update(value: value)
      flash[:errors] = @vote.errors.full_messages
    end

    redirect_to subforum_post_url(@subforum, @comment.post_id)
  end
end

app/views/comments/_comment.html.erb
<%= link_to comment.create_preview, subforum_post_comment_url(subforum, post, comment) %>
<%= comment.author.username %>
<section class="comment-score">
  Points: (<%= comment.points %>)
  <%= button_to "Upvote", upvote_subforum_post_comment_url(subforum, post, comment) %>
  <%= button_to "Downvote", downvote_subforum_post_comment_url(subforum, post, comment) %>
</section>

<% responses = comments_grouped_by_parent[comment.id] %>

<% if responses.length > 0 %>
  <section class="responses">
    <ul>
      <% responses.each do |child_comment| %>
        <li>
          <%= render "comments/comment",
            subforum: subforum,
            post: post,
            comment: child_comment,
            comments_grouped_by_parent: comments_grouped_by_parent %>
        </li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/comments/_form.html.erb
<!-- for updating and creating comments -->

<% action_url = comment.persisted? ? subforum_post_comment_url(comment) : subforum_post_comments_url %>
<% http_method = comment.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= http_method %>">

  <input type="hidden" name="comment[parent_comment_id]" value="<%= comment.parent_comment_id %>">

  <label for="body">Comment</label>
  <textarea id="body" name="comment[body]" placeholder="Write a response..."><%= comment.body %></textarea>

  <section class="buttons">
    <input id="submit" type="submit" value="Submit">
    <% if comment.persisted? %>
      <%= link_to "Cancel", subforum_post_comment_url(subforum, post, comment) %>
    <% else %>
      <%= link_to "Cancel", subforum_post_url(subforum, post) %>
    <% end %>
  </section>
</form>

app/views/comments/edit.html.erb
<section class="comments-edit">
  <h2>Edit Comment</h2>
  <%= button_to "Delete", subforum_post_comment_url(@subforum, @post, @comment), method: :delete %>
  <p>Subforum: <%= @subforum.title %></p>

  <section class="post">
    <h3>Original Post</h3>
    <p class="title"><%= @post.title %></p>
    <% url = @post.url %>
    <% if url && url != "" %>
      <p class="url">URL: <a href="http://<%= url %>"><%= url %></a></p>
    <% else %>
      <p class="url">URL: None</p>
    <% end %>
    <p><%= @post.body %></p>
  </section>

  <%= render "form", subforum: @subforum, post: @post, comment: @comment %>

  <section class="errors">
    <%= render "shared/errors" %>
  </section>
</section>

app/views/comments/new.html.erb
<section class="comments-new">
  <h2>New Comment</h2>
  <p>Subforum: <%= @subforum.title %></p>

  <section class="post">
    <h3>Original Post</h3>
    <p class="title"><%= @post.title %></p>
    <% url = @post.url %>
    <% if url && url != "" %>
      <p class="url">URL: <a href="http://<%= url %>"><%= url %></a></p>
    <% else %>
      <p class="url">URL: None</p>
    <% end %>
    <p><%= @post.body %></p>
  </section>

  <%= render "form", subforum: @subforum, post: @post, comment: @comment %>

  <section class="errors">
    <%= render "shared/errors" %>
  </section>
</section>

app/views/comments/show.html.erb
<section class="comments-show">
  <h2>Comment Details</h2>
  <p class="subforum">Subforum: <%= @subforum.title %></p>

  <section class="post">
    <h3>Original Post</h3>
    <p class="title"><%= @post.title %></p>
    <% url = @post.url %>
    <% if url && url != "" %>
      <p class="url">URL: <a href="http://<%= url %>"><%= url %></a></p>
    <% else %>
      <p class="url">URL: None</p>
    <% end %>
    <p><%= @post.body %></p>
  </section>

  <section class="comment">
    <h3>Comment</h3>
    <p><%= @comment.body %></p>

    <%= link_to "Edit comment", edit_subforum_post_comment_url(@subforum, @post, @comment) %>
    <%= link_to "Go back to post", subforum_post_url(@subforum, @post) %>

    <section class="responses">
      <h3>Responses</h3>
      <ul>
        <% @child_comments.each do |comment| %>
          <% if comment.id %> <!-- excludes the new comment -->
            <li>
              <%= link_to comment.create_preview, subforum_post_comment_url(@subforum, @post, comment) %>
              <%= comment.author.username %>
              <section class="comment-score">
                Points: (<%= comment.points %>)
              </section>
            </li>
          <% end %>
        <% end %>
      </ul>

      <section class="new-response">
        <%= render "form", subforum: @subforum, post: @post, comment: @child_comment %>
      </section>
    </section>
  </section>

  <section class="errors">
    <%= render "shared/errors" %>
  </section>
<section>