config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :subforums do
    resources :posts, except: [:index] do
      member do
        post "upvote"
        post "downvote"
      end

      resources :comments, except: [:index] do
        member do
          post "upvote"
          post "downvote"
        end
      end
    end
  end

  root to: redirect("/users/new")
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string           not null
#  last_name       :string           not null
#  email           :string           not null
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :first_name, :last_name, :email, :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  attr_reader :password

  has_many(
    :subforums,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Subforum
  )

  has_many(
    :posts,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Post
  )

  has_many(
    :comments,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Comment
  )

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    (user && user.is_password?(password)) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_out, only: [:new, :create]
  before_action :require_logged_in, only: [:show, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to subforums_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to subforums_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :username, :password)
  end
end

app/views/users/edit.html.erb
<section class="account-update">
  <h2>Update Account Details</h2>

  <form class="account-update-form" action="<%= user_url(@user) %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="PATCH">

    <section class="input-field">
      <label for="first-name">First name</label>
      <input id="first-name" type="text" name="user[first_name]" value="<%= @user.first_name %>">
    </section>

    <section class="input-field">
      <label for="first-name">Last name</label>
      <input id="last-name" type="text" name="user[last_name]" value="<%= @user.last_name %>">
    </section>

    <section class="input-field">
      <label for="first-name">Email</label>
      <input id="email" type="text" name="user[email]" value="<%= @user.email %>">
    </section>

    <input id="submit" type="submit" value="Update account">
  </form>

  <section class="errors">
    <%= render "shared/errors" %>
  </section>

  <a href="<%= subforums_url %>">Subforums</a>
</section>

app/views/users/new.html.erb
<section class="sign-up">
  <h2>Sign Up</h2>
  <img src="<%= image_url('logo.png') %>">

  <form class="sign-up-form" action="<%= users_url %>" method="post">
    <%= auth_token %>

    <section class="input-field">
      <label for="first-name">First name</label>
      <input id="first-name" type="text" name="user[first_name]" value="">
    </section>

    <section class="input-field">
      <label for="last-name">Last name</label>
      <input id="last-name" type="text" name="user[last_name]" value="">
    </section>

    <section class="input-field">
      <label for="email">Email</label>
      <input id="email" type="text" name="user[email]" value="">
    </section>

    <section class="input-field">
      <label for="username">Username</label>
      <input id="username" type="text" name="user[username]" value="">
    </section>

    <section class="input-field">
      <label for="password">Password</label>
      <input id="password" type="password" name="user[password]" value="">
    </section>

    <input id="submit" type="submit" value="Sign up">
  </form>

  <section class="errors">
    <%= render "shared/errors" %>
  </section>
</section>

<form class="guest-button" action="<%= session_url %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="user[username]" value="Guest">
  <input type="hidden" name="user[password]" value="123456">

  <input id="submit" type="submit" value= "Log in as Guest">
</form>