config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :subforums do
    resources :posts, except: [:index] do
      member do
        post "upvote"
        post "downvote"
      end

      resources :comments, except: [:index] do
        member do
          post "upvote"
          post "downvote"
        end
      end
    end
  end

  root to: redirect("/users/new")
end

app/models/subforum.rb
# == Schema Information
#
# Table name: subforums
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Subforum < ApplicationRecord
  validates :title, :moderator, presence: true
  validates :title, uniqueness: true

  belongs_to(
    :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User
  )

  has_many :posts,
    dependent: :destroy

  has_many(
    :comments,
    through: :posts,
    source: :comments,
    dependent: :destroy
  )
end

app/controllers/subforums_controller.rb
class SubforumsController < ApplicationController
  before_action :require_logged_in, only: [:create, :new, :edit, :update, :destroy]
  before_action :require_current_user_owns_subforum, only: [:edit, :update, :destroy]

  def index
    @subforums = Subforum.all
  end

  def create
    @subforum = current_user.subforums.new(subforum_params)

    if @subforum.save
      redirect_to subforum_url(@subforum)
    else
      flash.now[:errors] = @subforum.errors.full_messages
      render :new
    end
  end

  def new
    @subforum = Subforum.new
  end

  def edit
    @subforum = Subforum.find(params[:id])
  end

  def show
    @subforum = Subforum.find(params[:id])
  end

  def update
    @subforum = Subforum.find(params[:id])

    if @subforum.update(subforum_params)
      redirect_to subforum_url(@subforum)
    else
      flash.now[:errors] = @subforum.errors.full_messages
      render :edit
    end
  end

  def destroy
    @subforum = Subforum.find(params[:id])
    @subforum.delete
    redirect_to subforums_url
  end

  private

  def require_current_user_owns_subforum
    return if current_user.subforums.find_by(id: params[:id])
    @subforum = Subforum.find(params[:id])
    flash[:errors] = ["You are not the creator of this subforum"]
    redirect_to subforum_url(@subforum)
  end

  def subforum_params
    params.require(:subforum).permit(:title, :description)
  end
end

app/views/subforums/_form.html.erb
<!-- for updating or creating a subforum -->

<% action_url = subforum.persisted? ? subforum_url(subforum) : subforums_url %>
<% http_method = subforum.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= http_method %>">

  <section class="input-field">
    <label for="title">Title</label>
    <input id="title" type="text" name="subforum[title]" value="<%= subforum.title %>">
  </section>

  <label for="form-description">Description (Optional)</label>
  <textarea id="description" name="subforum[description]"><%= subforum.description %></textarea>

  <section class="buttons">
    <input id="submit" type="submit" value="Submit">
    <% if subforum.persisted? %>
      <%= link_to "Cancel", subforum_url(subforum) %>
    <% else %>
      <%= link_to "Cancel", subforums_url %>
    <% end %>
  </section>
</form>

<section class="errors">
  <%= render "shared/errors" %>
</section>

app/views/subforums/edit.html.erb
<section class="subforums-edit">
  <h2>Edit Subforum</h2>
  <%= button_to "Delete", subforum_url(@subforum), method: :delete %>
  <%= render "form", subforum: @subforum %>
</section>

app/views/subforums/index.html.erb
<section class="subforums-index">
  <h2>Subforums</h2>

  <ul>
    <% @subforums.each do |subforum| %>
      <li>
        <%= link_to subforum.title, subforum_url(subforum) %>
        <%= subforum.moderator.username %>
      </li>
    <% end %>
  </ul>

  <%= link_to "Create a new subforum", new_subforum_url %>
</section>

app/views/subforums/new.html.erb
<section class="subforums-new">
  <h2>New Subforum</h2>
  <%= render "form", subforum: @subforum %>
</section>

app/views/subforums/show.html.erb
<% description = @subforum.description %>

<section class="subforums-show">
  <h2><%= @subforum.title %></h2>

  <section class="description">
    <h3>Description</h3>
    <p><%= description == "" ? "None" : description %></p>
  </section>

  <%= link_to "Edit subforum", edit_subforum_url(@subforum) %>
  <%= link_to "See all subforums", subforums_url %>
  
  <section class="errors">
    <%= render "shared/errors" %>
  </section>

  <section class="posts">
    <h3>Posts</h3>
    <ul>
      <% @subforum.posts.each do |post| %>
        <li>
          <%= link_to post.title, subforum_post_url(post.subforum_id, post) %>
          <%= post.author.username %>
          <section class="post-score">
            Points: (<%= post.points %>)
            <%= button_to "Upvote", upvote_subforum_post_url(post.subforum_id, post) %>
            <%= button_to "Downvote", downvote_subforum_post_url(post.subforum_id, post) %>
          </section>
        </li>
      <% end %>
    </ul>

    <%= link_to "Create a new post", new_subforum_post_url(subforum_id: @subforum.id) %>
  </section>
</section>