config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :subforums do
    resources :posts, except: [:index] do
      member do
        post "upvote"
        post "downvote"
      end

      resources :comments, except: [:index] do
        member do
          post "upvote"
          post "downvote"
        end
      end
    end
  end

  root to: redirect("/users/new")
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  url         :string
#  body        :text             not null
#  subforum_id :integer          not null
#  author_id   :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ApplicationRecord
  include Votable

  validates :title, :body, :subforum, :author, presence: true
  validates :title, uniqueness: true

  belongs_to :subforum

  belongs_to(
    :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User
  )

  has_many :comments,
    dependent: :destroy

  def comments_grouped_by_parent
    comments_grouped_by_parent = Hash.new { |hash, key| hash[key]= [] }

    self.comments.includes(:author).each do |comment|
      comments_grouped_by_parent[comment.parent_comment_id] << comment
    end

    comments_grouped_by_parent
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, only: [:create, :new, :edit, :update, :destroy]
  before_action :require_current_user_owns_post, only: [:edit, :update]
  before_action :require_current_user_owns_post_or_subforum, only: [:destroy]

  def create
    @post = current_user.posts.new(post_params)
    @post.subforum_id = params[:subforum_id]
    @subforum = @post.subforum

    if @post.save
      redirect_to subforum_post_url(@post.subforum_id, @post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def new
    @post = Post.new
    @subforum = Subforum.find_by(id: params[:subforum_id])
  end

  def edit
    @post = Post.find(params[:id])
    @subforum = @post.subforum
  end

  def show
    @post = Post.find(params[:id])
    @subforum = @post.subforum
  end

  def update
    @post = Post.find(params[:id])
    @subforum = @post.subforum

    if @post.update(post_params)
      redirect_to subforum_post_url(@post.subforum_id, @post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to subforum_url(@post.subforum_id)
  end

  def upvote
    vote(1)
  end

  def downvote
    vote(-1)
  end

  private

  def require_current_user_owns_post
    return if current_user.posts.find_by(id: params[:id])
    @post = Post.find(params[:id])
    flash[:errors] = ["You are not the creator of this post"]
    redirect_to subforum_post_url(@post.subforum_id, @post)
  end

  def require_current_user_owns_post_or_subforum
    return if (
    current_user.subforums.find_by(id: params[:subforum_id]) || current_user.posts.find_by(id: params[:id])
    )
    @post = Post.find(params[:id])
    flash[:errors] = ["You are not the post's creator or subforum's moderator"]
    redirect_to subforum_post_url(@post.subforum_id, @post)
  end

  def post_params
    params.require(:post).permit(:title, :url, :body)
  end

  def vote(value)
    @post = Post.find(params[:id])
    @vote = @post.votes.find_or_initialize_by(user: current_user)

    unless @vote.update(value: value)
      flash[:errors] = @vote.errors.full_messages
    end

    redirect_to subforum_url(@post.subforum_id)
  end
end

app/views/posts/_form.html.erb
<!-- for updating and creating posts -->

<% action_url = post.persisted? ? subforum_post_url(post) : subforum_posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= http_method %>">

  <section class="title-input-field">
    <label for="title">Title</label>
    <input id="title" type="text" name="post[title]" value="<%= post.title %>">
  </section>

  <section class="url-input-field">
    <label for="url">URL (Optional)</label>
    <input id="url" type="text" name="post[url]" value="<%= post.url %>">
  </section>

  <label for="body">Body</label>
  <textarea id="body" name="post[body]"><%= post.body %></textarea>

  <section class="buttons">
    <input id="submit" type="submit" value="Submit">
    <% if post.persisted? %>
      <%= link_to "Cancel", subforum_post_url(subforum, post) %>
    <% else %>
      <%= link_to "Cancel", subforum_url(subforum) %>
    <% end %>
  </section>
</form>

<section class="errors">
  <%= render "shared/errors" %>
</section>

app/views/posts/edit.html.erb
<section class="posts-edit">
  <h2>Edit Post</h2>
  <p>Subforum: <%= @subforum.title %></p>

  <%= render "form", subforum: @subforum, post: @post %>
</section>

app/views/posts/new.html.erb
<section class="posts-new">
  <h2>New Post</h2>
  <p>Subforum: <%= @subforum.title %></p>

  <%= render "form", subforum: @subforum, post: @post %>
</section>

app/views/posts/show.html.erb
<% url = @post.url %>

<section class="posts-show">
  <h2><%= @post.title %></h2>

  <section class="info">
    <p>Subforum: <%= @subforum.title %></p>
    <% if url && url != "" %>
      <p>URL: <a href="http://<%= url %>"><%= url %></a></p>
    <% else %>
      <p>URL: None</p>
    <% end %>
  </section>

  <p><%= @post.body %></p>

  <%= button_to "Delete", subforum_post_url(@post.subforum_id, @post), method: :delete %>
  <%= link_to "Edit post", edit_subforum_post_url(@post.subforum_id, @post) %>
  <%= link_to "Go back to subforum", subforum_url(@post.subforum_id) %>

  <section class="errors">
    <%= render "shared/errors" %>
  </section>

  <section class="comments">
    <h3>Comments</h3>
    <ul>
      <% comments_grouped_by_parent = @post.comments_grouped_by_parent %>

      <% comments_grouped_by_parent[nil].each do |top_level_comment| %>
        <li>
          <%= render "comments/comment",
            subforum: @subforum,
            post: @post,
            comment: top_level_comment,
            comments_grouped_by_parent: comments_grouped_by_parent %>
        </li>
      <% end %>
    </ul>

    <%= link_to "Write a new comment", new_subforum_post_comment_url(subforum_id: @subforum.id, post_id: @post.id) %>
  </section>
</section>